### ISSUE TITLE
CLI

### ISSUE THREAD

**Issue by divmain** [interlockjs/interlock#18]
## Deliverables

- [ ] should support the common 80% of use cases
- [ ] no config necessary
- [ ] config inferred from `package.json`
- [ ] should only need to provide input module path and output bundle path

### [vantage.js](https://github.com/dthree/vantage)

**Pros:**

- debug compilation problems interactively, as they come up
- enter configuration as its needed, and then output a config file at the end to reproduce the compilation
- integrate with the dev server
- integrate with other plugins

**Cons:**

- more complex than other available options

**Comment by divmain** [comment]
@baer, you interested in looking into this?  Maybe start by enumerating the available options.  I saw `vantage.js` just now, and there is the possibility for some neat interactions with the plugin system.  But something simpler may be more pragmatic for a v1.0 release.

**Comment by baer** [comment]
Yea I saw that too. Looks neat but I'm not yet sure what it would buy this
project. Maybe something with the yet to be finished seventh server. I do
like commander which is what this is based off of. Any problem with using
commander to start out with?

**Comment by divmain** [comment]
No problem using commander.  `vantage` looked interesting because it opens the door to more interactivity with the compilation process, and along with that some power and user-friendliness.

For example, you don't really know what split points you want, so you start the process.  It identifies all the modules in the dependency graph, shows them to you, along with some metadata - things like number of dependencies, number of places required, KB of JS included in module+dependencies.  Then it could prompt you "would you like to insert a split point at any of these modules?"

I'm sure there are a number of use cases where it would be helpful or interesting to pause the compilation process, display data to the user, and prompt for input before continuing.

If this seems like a worthwhile idea, it would be worth starting with `vantage` and just using the subset of features that overlap with commander.  Then we could add an interactive mode in small pieces.

**Comment by baer** [comment]
I'll look at how hard it is to use. The initial commit was only on May 29
so I kinda expect a lot of churn. It also says "inspired by and based on
commander.js" and from what I can see the flu definitions are the same so
there is a very clear upgrade path. I'll play with it a bit and see.

**Comment by divmain** [comment]
Fair enough.  Thanks!
