### ISSUE TITLE
Rip out streams

### ISSUE THREAD

**Issue by divmain** [interlockjs/interlock#58]
As my understanding and experience with Most monadic streams has progressed, I've identified a number of characteristics of those streams that don't align well with the problem space.  Unfortunately, they don't seem well suited to Interlock and add subtle complexity.

**Goal:** Remove `most` as a dependency, and replace all previous operations with `bluebird`.  Promises will be the foundational primitive of Interlock async behavior.

**Comment by izaakschroeder** [comment]
May they rest in peace. :cry:

**Comment by baer** [comment]
I didn't see this coming
